# Generated by Django 2.2 on 2022-04-12 21:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentWeiboInfo',
            fields=[
                ('wb_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='微博的ID')),
                ('wb_userId', models.CharField(max_length=50, verbose_name='微博用户的ID')),
                ('wb_userName', models.CharField(max_length=50, verbose_name='微博用户的昵称')),
                ('wb_user_profile_image_url', models.TextField(verbose_name='微博用户的头像')),
                ('wb_created_at', models.DateTimeField(blank=True, verbose_name='微博创建时间')),
                ('wb_source', models.TextField(blank=True, verbose_name='微博来源')),
                ('wb_text', models.TextField(verbose_name='微博内容')),
                ('wb_pic_ids', models.TextField(blank=True, verbose_name='微博图片')),
                ('wb_reposts', models.IntegerField(blank=True, default=0, verbose_name='转载数')),
                ('wb_comments', models.IntegerField(blank=True, default=0, verbose_name='评论数')),
                ('wb_like', models.IntegerField(blank=True, default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '微博评论',
                'verbose_name_plural': '微博评论',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, verbose_name='爬取用户')),
                ('cookie', models.TextField(blank=True, verbose_name='设置cookie')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '爬虫设置',
                'verbose_name_plural': '爬虫设置',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户id')),
                ('Image', models.TextField(verbose_name='用户头像')),
                ('NickName', models.CharField(max_length=30, verbose_name='昵称')),
                ('Gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别')),
                ('Province', models.CharField(blank=True, max_length=30, verbose_name='所在省')),
                ('City', models.CharField(blank=True, max_length=30, verbose_name='所在城市')),
                ('BriefIntroduction', models.CharField(blank=True, max_length=500, verbose_name='简介')),
                ('Birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('Constellation', models.CharField(blank=True, max_length=30, verbose_name='星座')),
                ('Num_Tweets', models.IntegerField(default=0, verbose_name='微博数')),
                ('Num_Follows', models.IntegerField(default=0, verbose_name='关注数')),
                ('Num_Fans', models.IntegerField(blank=True, default=0, verbose_name='粉丝数')),
                ('SexOrientation', models.CharField(blank=True, max_length=30, verbose_name='性取向')),
                ('Sentiment', models.CharField(blank=True, max_length=30, verbose_name='感情状况')),
                ('VIPlevel', models.CharField(blank=True, max_length=30, verbose_name='会员等级')),
                ('Authentication', models.CharField(blank=True, max_length=30, verbose_name='认证')),
                ('URL', models.CharField(blank=True, max_length=300, verbose_name='首页链接')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='TweetsInfo',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='微博ID')),
                ('Content', models.TextField(verbose_name='微博内容')),
                ('PubTime', models.DateTimeField(blank=True, verbose_name='发表时间')),
                ('Co_oridinates', models.CharField(blank=True, max_length=300, verbose_name='定位坐标')),
                ('Tools', models.CharField(blank=True, max_length=300, verbose_name='发布工具')),
                ('Like', models.IntegerField(blank=True, default=0, verbose_name='点赞数')),
                ('Comment', models.IntegerField(blank=True, default=0, verbose_name='评论数')),
                ('Transfer', models.IntegerField(blank=True, default=0, verbose_name='转载数')),
                ('tags', models.TextField(blank=True, verbose_name='标签')),
                ('pinyin', models.TextField(blank=True, verbose_name='词性')),
                ('sentiments', models.CharField(blank=True, max_length=50, verbose_name='情感值')),
                ('crawl_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='添加时间')),
                ('UserInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpiderAPI.UserInfo', verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '微博信息',
                'verbose_name_plural': '微博信息',
            },
        ),
        migrations.CreateModel(
            name='ImgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordcloud', models.TextField(blank=True, verbose_name='微博词云')),
                ('UserInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpiderAPI.UserInfo', verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '微博词云',
                'verbose_name_plural': '微博词云',
            },
        ),
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('c_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='评论的ID')),
                ('c_created_at', models.DateTimeField(blank=True, verbose_name='评论创建时间')),
                ('c_source', models.TextField(blank=True, verbose_name='评论的来源')),
                ('c_text', models.TextField(blank=True, verbose_name='评论的内容')),
                ('c_like_num', models.IntegerField(blank=True, default=0, verbose_name='评论点赞数')),
                ('c_userId', models.CharField(blank=True, max_length=50, verbose_name='评论用户的微博ID')),
                ('c_user_name', models.CharField(blank=True, max_length=300, verbose_name='评论用户的微博昵称')),
                ('C_profile_image_url', models.TextField(blank=True, verbose_name='评论用户的头像')),
                ('C_profile_url', models.TextField(blank=True, verbose_name='评论用户的主页')),
                ('CommentWeiboInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpiderAPI.CommentWeiboInfo', verbose_name='微博用户信息')),
            ],
            options={
                'verbose_name': '评论详情',
                'verbose_name_plural': '评论详情',
            },
        ),
    ]
